import localFont from "next/font/local";
import "./globals.css";
import "./component/sidebar";
import SideBar from "./component/sidebar";
import Navbar from "./component/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Projet Cars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="">
            <Navbar />
          </div>
          <div className="">
            <SideBar />
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
