import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./component/sidebar";
import Navbar from "./component/navbar";
//import { usePathname } from 'next/navigation';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata pour le site
export const metadata = {
  title: "Projet Cars",
  description: "Generated by create next app",
};

// Composant de layout racine
export default function RootLayout({ children }) {
  // const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`bg-[#D7D7D7] h-svh ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Vérifie si la page est '/auth' */}
        {/* {pathname.startsWith('/auth') ? (
          children // Pas de layout global pour /auth
        ) : ( */}
          <div className="flex flex-col md:flex-row md:h-full overflow-hidden">
            <div className=" hidden md:w-1/4 md:flex overflow-y-auto h-full py-5 rounded-r-lg justify-around w-full max-w-[300px] bg-[#7AA6E3]">
              <SideBar />
            </div>
            <div className="md:w-3/4 flex-col w-full lg:w-full">
              <Navbar />
              <div className="hidden md:flex">{children}</div>
            </div>
            <div className="flex md:hidden">{children}</div>
          </div>
       
      </body>
    </html>
  );
}
